apiVersion: v1
kind: Service
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app: {{ .Values.name }}
status:
  loadBalancer: {}
