apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: forms-flow-bpm
  name: forms-flow-bpm
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: forms-flow-bpm:latest
  postCommit: {}
  resources:
    limits:
      cpu: "1"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  runPolicy: Serial
  source:
    contextDir: {{ .Values.source_context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    sourceSecret:
      name: github-token
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: openshift_custom_Dockerfile
      pullSecret:
        name: artifacts-default-kpfslj
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
