apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: camunda
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
