apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  DATABASE_USERNAME: "{{ .Values.postgresql.username }}"
  DATABASE_NAME: "{{ .Values.postgresql.databasename }}"
  DATABASE_PASSWORD: "{{ .Values.postgresql.password }}"
  DATABASE_HOST: "{{ .Values.postgresql.host }}"