apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbGFucmFqdTAwNyIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQ0Z3OTdJeUpmY3hpblNfQXpaOGlBcDlvSVkwIiwiYXV0aCI6IllXeGhibkpoYW5Vd01EYzZaR05yY2w5d1lYUmZRMFozT1RkSmVVcG1ZM2hwYmxOZlFYcGFPR2xCY0RsdlNWa3cifX19