ingress: 
  enabled: true # create an ingress for this component 
  port: 7000
  tls: 
    hosts: 
      - "apps.devops.aot-technologies.com"
  url: "forms-flow-analytics.apps.devops.aot-technologies.com" # sets the forms-flow-analytics API url

postgresql:
  auth:
    database: forms-flow-analytics # Name for custom database to create
    postgresPassword: postgres # Password for the "postgres" admin user
    password: forms-flow-analytics  # Password for the custom user to create
    userName: forms-flow-analytics  # Name for a custom user to create
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 14.2.0-debian-10-r57
  primary:
    containerSecurityContext:
      enabled: false
    persistence:
      mountPath: /var/lib/pgsql/data
      storageClass: nfs-client 
      size: 1Gi 
    podSecurityContext:
      enabled: false
    service:
      ports:
        postgresql: 5432  # PostgreSQL service port
    shmVolume:
      chmod:
        enabled: false
  volumePermissions:
    containerSecurityContext:
      runAsUser: "auto"

redisExporter:
  exporter:
    image:  
      registry: docker.io
      repository: oliver006/redis_exporter
      tag: v1.14.0-alpine
  redis:
    image:  
      registry: docker.io
      repository: redis
      tag: 7.0-rc3-alpine
  persistentVolumeClaim:
    size: 2Gi # storage class name 
    storageClass: nfs-client # pvc request size
  resources:
    limits:
      cpu: 60m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

redash:
  image:
    registry: docker.io #registry to use
    repository: redash/redash # repoisitory for redash image  
    tag: latest # tag of image being used
  database:
    password: postgres # admin password
    url: "postgresql://postgres:postgres@forms-flow-analytics-postgresql:5432/postgres" # redash database url - i.e forms-flow-analytics-postgresql


resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 180m
    memory: 1Gi
