Domain: foo #<DEFINE_ME>

postgresql:
  host: forms-flow-ai-postgresql-ha-pgpool
  port: 5432

  username: postgres
  password: postgres

  externalSecret:
    name: 
    usernameKey: username
    passwordKey: password

formsflow:
  auth: forms-flow-ai-auth

ingress:
  ingressClassName: "" 
  annotations: 
  enabled: true # create an ingress for this component
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5000
  tls: true
  selfSigned: false
  extraTls:
    - {}  

redis-exporter:
  exporter:
    image:  
      registry: docker.io
      repository: oliver006/redis_exporter
      tag: v1.14.0-alpine
  redis:
    image:  
      registry: docker.io
      repository: redis
      tag: 7.0-rc3-alpine
  persistentVolumeClaim:
    size: 2Gi  
    storageClass: ""
  resources:
    limits:
      cpu: 60m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi

redash:
  image:
    registry: docker.io #registry to use
    repository: formsflow/redash # repoisitory for redash image  
    tag: 10.1.5 # tag of image being used
  config:
    cookie_secret: 'redash-selfhosted'
    secret_key: 'redash-selfhosted'

resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 180m
    memory: 1Gi
