cpu_limit: 850m
cpu_request: 700m
memory_limit: 2Gi
memory_request: 1Gi
tag_name: latest
source_repository_ref: master 
source_repository_url: https://github.com/AOT-Technologies/forms-flow-ai
source_context_dir: /forms-flow-forms
