apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Chart.Name }}:{{ .Values.image_tag }}"
  postCommit: {}
  resources:
    limits:
      cpu: "{{ .Values.cpu_limit }}"
      memory: "{{ .Values.memory_limit }}"
    requests:
      cpu: "{{ .Values.cpu_request }}"
      memory: "{{ .Values.memory_request }}"
  runPolicy: Serial
  source:
    contextDir: {{ .Values.source_context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
