apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-web
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  KEYCLOAK_CLIENT: "{{tpl .Values.webclient .}}"
  APPLICATION_NAME: "{{tpl .Values.webname .}}"
  USER_ACCESS_PERMISSIONS: "{{ .Values.UserAccesPermissions }}"
  PUBLIC_WORKFLOW_ENABLED: "false"
  OPENTELEMETRY_SERVICE: "false"
  WEB_BASE_CUSTOM_URL: "{{tpl .Values.web.base_custom_url .}}"
  CUSTOM_THEME_URL: "{{tpl .Values.web.custom_theme_url .}}"
  ENABLE_FORMS_MODULE: "true"
  ENABLE_TASKS_MODULE: "true"
  ENABLE_DASHBOARDS_MODULE: "true"
  ENABLE_PROCESSES_MODULE: "true"
  ENABLE_APPLICATIONS_MODULE: "true"
  REACT_APP_LANGUAGE: "{{tpl .Values.Language .}}"