apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-web
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  KEYCLOAK_CLIENT: "{{ tpl .Values.webclient . }}"
  APPLICATION_NAME: "{{ tpl .Values.webname . }}"
  USER_ACCESS_PERMISSIONS: "{{ .Values.UserAccesPermissions }}"
  PUBLIC_WORKFLOW_ENABLED:  "{{ tpl .Values.web.public_workflow_enabled . }}"
  OPENTELEMETRY_SERVICE:  "{{ tpl .Values.web.opentelemetry_service . }}"
  WEB_BASE_CUSTOM_URL: "{{ tpl .Values.web.base_custom_url . }}"
  CUSTOM_THEME_URL: "{{ tpl .Values.web.custom_theme_url . }}"
  ENABLE_FORMS_MODULE: "{{ tpl .Values.web.enable_forms_module . }}"
  ENABLE_TASKS_MODULE: "{{ tpl .Values.web.enable_tasks_module . }}"
  ENABLE_DASHBOARDS_MODULE: "{{ tpl .Values.web.enable_dashboards_module . }}"
  ENABLE_PROCESSES_MODULE: "{{ tpl .Values.web.enable_processes_module . }}"
  ENABLE_APPLICATIONS_MODULE: "{{ tpl .Values.web.enable_applications_module . }}"
  REACT_APP_LANGUAGE: "{{ tpl .Values.Language . }}"
  REACT_APP_SHOW_PREMIUM_ICON: "{{ tpl .Values.ShowPremiumIcon . }}"
  REACT_APP_IS_ENTERPRISE: "{{ tpl .Values.IsEnterPrise . }}"
  REACT_APP_CLARITY_KEY: "{{ tpl .Values.ClarityKey . }}"
