---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  KEYCLOAK_CLIENT: "{{ .Chart.Name }}"
  APPLICATION_NAME: "{{ .Chart.Name }}"
  USER_ACCESS_PERMISSIONS: ''
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}-config.template
  name: {{ .Chart.Name }}-config.template
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "NODE_ENV": "${NODE_ENV}",
        "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
        "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}", 
        "REACT_APP_BPM_URL": "${REACT_APP_BPM_URL}", 
        "REACT_APP_KEYCLOAK_CLIENT": "${REACT_APP_KEYCLOAK_CLIENT}", 
        "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}", 
        "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "${REACT_APP_WEBSOCKET_ENCRYPT_KEY}", 
        "REACT_APP_KEYCLOAK_URL_REALM": "${REACT_APP_KEYCLOAK_URL_REALM}", 
        "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
        "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
        "REACT_APP_USER_ACCESS_PERMISSIONS": "${REACT_APP_USER_ACCESS_PERMISSIONS}",
        "REACT_APP_MT_ADMIN_BASE_URL": "${REACT_APP_MT_ADMIN_BASE_URL}",
        "REACT_APP_MT_ADMIN_BASE_URL_VERSION": "v1"

      }
