---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  CLIENT_ROLE: "formsflow-client"
  STAFF_DESIGNER_ROLE: "formsflow-designer"
  STAFF_REVIEWER_ROLE: "formsflow-reviewer"
  ANONYMOUS_ID: "61856bbc69b6301d70977ae1"
  STAFF_REVIEWER_ID: "61856bbc69b630461b977ae2"
  CLIENT_ID: "61856bbc69b630461b977ae3"
  USER_RESOURCE_FORM_ID: "61856bbc69b6301d70977ae4"
  STAFF_DESIGNER_ID: "61856bbc69b630f304977adf"
  KEYCLOAK_CLIENT: "{{ .Chart.Name }}"
  APPLICATION_NAME: "{{ .Chart.Name }}"
  USER_ACCESS_PERMISSIONS: ''
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}-config.template
  name: {{ .Chart.Name }}-config.template
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "NODE_ENV": "${NODE_ENV}",
        "REACT_APP_CLIENT_ROLE": "${REACT_APP_CLIENT_ROLE}",
        "REACT_APP_STAFF_DESIGNER_ROLE": "${REACT_APP_STAFF_DESIGNER_ROLE}",
        "REACT_APP_STAFF_REVIEWER_ROLE": "${REACT_APP_STAFF_REVIEWER_ROLE}",
        "REACT_APP_CLIENT_ID": "${REACT_APP_CLIENT_ID}",
        "REACT_APP_STAFF_REVIEWER_ID": "${REACT_APP_STAFF_REVIEWER_ID}",
        "REACT_APP_STAFF_DESIGNER_ID": "${REACT_APP_STAFF_DESIGNER_ID}",
        "REACT_APP_USER_RESOURCE_FORM_ID": "${REACT_APP_USER_RESOURCE_FORM_ID}",
        "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
        "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}", 
        "REACT_APP_CAMUNDA_API_URI": "${REACT_APP_CAMUNDA_API_URI}", 
        "REACT_APP_KEYCLOAK_CLIENT": "${REACT_APP_KEYCLOAK_CLIENT}", 
        "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}", 
        "REACT_APP_ANONYMOUS_ID": "${REACT_APP_ANONYMOUS_ID}", 
        "REACT_APP_INSIGHTS_API_BASE": "${REACT_APP_INSIGHTS_API_BASE}", 
        "REACT_APP_INSIGHTS_API_KEY": "${REACT_APP_INSIGHTS_API_KEY}", 
        "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "${REACT_APP_WEBSOCKET_ENCRYPT_KEY}", 
        "REACT_APP_KEYCLOAK_URL_REALM": "${REACT_APP_KEYCLOAK_URL_REALM}", 
        "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
        "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
        "REACT_APP_USER_ACCESS_PERMISSIONS": "${REACT_APP_USER_ACCESS_PERMISSIONS}",
        "REACT_APP_FORMIO_JWT_SECRET": "${REACT_APP_FORMIO_JWT_SECRET}",
        "REACT_APP_MT_ADMIN_BASE_URL": "${REACT_APP_MT_ADMIN_BASE_URL}",
        "REACT_APP_MT_ADMIN_BASE_URL_VERSION": "v1"

      }
