apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-template-configuration" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-web
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "NODE_ENV": "${NODE_ENV}",
        "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
        "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}", 
        "REACT_APP_BPM_URL": "${REACT_APP_BPM_URL}", 
        "REACT_APP_KEYCLOAK_CLIENT": "${REACT_APP_KEYCLOAK_CLIENT}", 
        "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}", 
        "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "${REACT_APP_WEBSOCKET_ENCRYPT_KEY}", 
        "REACT_APP_KEYCLOAK_URL_REALM": "${REACT_APP_KEYCLOAK_URL_REALM}", 
        "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
        "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
        "REACT_APP_USER_ACCESS_PERMISSIONS": "${REACT_APP_USER_ACCESS_PERMISSIONS}",
        "REACT_APP_MT_ADMIN_BASE_URL": "${REACT_APP_MT_ADMIN_BASE_URL}",
        "REACT_APP_MT_ADMIN_BASE_URL_VERSION": "v1",
        "REACT_APP_MULTI_TENANCY_ENABLED": "${REACT_APP_MULTI_TENANCY_ENABLED}",
        "REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH": "${REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH}",
        "REACT_APP_CUSTOM_SUBMISSION_URL": "${REACT_APP_CUSTOM_SUBMISSION_URL}",
        "REACT_APP_CUSTOM_SUBMISSION_ENABLED": "${REACT_APP_CUSTOM_SUBMISSION_ENABLED}",
        "REACT_APP_DOCUMENT_SERVICE_URL": "${REACT_APP_DOCUMENT_SERVICE_URL}",
        "REACT_APP_DRAFT_ENABLED": "${REACT_APP_DRAFT_ENABLED}",
        "REACT_APP_DRAFT_POLLING_RATE": "${REACT_APP_DRAFT_POLLING_RATE}",
        "REACT_APP_EXPORT_PDF_ENABLED": "${REACT_APP_EXPORT_PDF_ENABLED}",
        "REACT_APP_LANGUAGE": "${REACT_APP_LANGUAGE}",
        "REACT_APP_OPENTELEMETRY_SERVICE": "${OPENTELEMETRY_SERVICE}",
        "REACT_APP_PUBLIC_WORKFLOW_ENABLED": "${REACT_APP_PUBLIC_WORKFLOW_ENABLED}",
        "REACT_APP_WEB_BASE_CUSTOM_URL": "${WEB_BASE_CUSTOM_URL}",
        "REACT_APP_CUSTOM_THEME_URL": "${CUSTOM_THEME_URL}",
        "ENABLE_FORMS_MODULE": "${ENABLE_FORMS_MODULE}",
        "ENABLE_TASKS_MODULE": "${ENABLE_TASKS_MODULE}",
        "ENABLE_DASHBOARDS_MODULE": "${ENABLE_DASHBOARDS_MODULE}",
        "ENABLE_PROCESSES_MODULE": "${ENABLE_PROCESSES_MODULE}",
        "ENABLE_APPLICATIONS_MODULE": "${ENABLE_APPLICATIONS_MODULE}",
        "REACT_APP_ENABLE_CHATBOT": "${REACT_APP_ENABLE_CHATBOT}",
        "REACT_APP_CHATBOT_URL": "${REACT_APP_CHATBOT_URL}",
        "REACT_APP_ENABLE_LOW_CODE_DESIGNER": "${ENABLE_LOW_CODE_DESIGNER}",
        "REACT_APP_KEYCLOAK_URL_HTTP_RELATIVE_PATH": "${KEYCLOAK_URL_HTTP_RELATIVE_PATH}",
        "REACT_APP_SHOW_PREMIUM_ICON": "${REACT_APP_SHOW_PREMIUM_ICON}",
        "REACT_APP_IS_ENTERPRISE": "${REACT_APP_IS_ENTERPRISE}",
        "REACT_APP_CLARITY_KEY": "${REACT_APP_CLARITY_KEY}",
        "REACT_APP_USER_NAME_DISPLAY_CLAIM": "${USER_NAME_DISPLAY_CLAIM:-preferred_username}"
      }