---
Domain: #<DEFINE_ME>
formsflowdb:
  postgresql:
    fullnameOverride: forms-flow-ai-postgresql-ha-pgpool
    enabled: true
    database: postgres
  service:
    ports:
      postgresql: 5432
forms-flow-bpm:
  clientid: "forms-flow-bpm"
  clientsecret: "786001d6-68a8-4519-903c-bc5b5a870d68"
  ingress:
      hostname: forms-flow-bpm-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-forms:
  admin:
    email: "me@defineme.com"
    password: "admin"
  ingress:
    hostname: forms-flow-forms-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-api:
  ingress:
      hostname: forms-flow-api-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-admin:
  ingress:
      hostname: forms-flow-admin-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-documents-api:
  ingress:
      hostname: forms-flow-documents-api-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-data-analysis:
  ingress:
      hostname: forms-flow-data-analysis-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-analytics:
  ingress:
      hostname: forms-flow-analytics-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-idm:
  keycloak:
    ingress:
      hostname: forms-flow-idm-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
  realm: forms-flow-ai
  context-path: /auth

forms-flow-web:
  clientid: forms-flow-web
  ingress:
      hostname: forms-flow-web-{{.Release.Namespace}}.{{tpl (.Values.Domain) .}}
forms-flow-auth:
  imagesecret: "#DEFINE_ME"


mongodb:
  image:
    tag: 4.2.21-debian-10-r8
  enabled: true
  fullnameOverride: "forms-flow-ai-mongodb"
  clusterDomain: cluster.local
  architecture: replicaset
  useStatefulSet: true
  auth:
    databases: 
      - formsflow 
    passwords:
      - changeme    #use the same password in initdbscript
    usernames:
      - mongodb     #use the same username in initdbscript
    enabled: true
    rootUser: root
    rootPassword: "changeme"
    replicaSetKey: "formsflow"
  initdbScripts:
     init-mongo.js: |
           use admin
           db.createUser({
              user: 'mongodb',     
              pwd: 'changeme',   
              roles: [
                {
                   role: 'readWrite',
                   db: 'formsflow',
                },
              ],
           });
  replicaSetName: rs0
  replicaSetHostnames: true
  directoryPerDB: false
  replicaCount: 3
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
  containerPorts:
    mongodb: 27017
  service:
    nameOverride: "forms-flow-ai-mongodb"
    type: ClusterIP
    portName: mongodb
    ports:
      mongodb: 27017
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /bitnami/mongodb
  serviceAccount:
    create: true
  
  arbiter:
    enabled: false
    podSecurityContext:
    enabled: false
    fsGroup: 1001
    containerSecurityContext:
    enabled: false
    runAsUser: 1001

websocket_encrypt_key: "FormsFlow.AI"
insight_api_key: ""
redis_host: ""
redis_port: ""
redis_pass_code: ""
draft_enabled: "true"
export_pdf_enabled: "false"
elastic_server: "forms-flow-elastic:9200"
redis_url: "redis://redis-exporter:6379/1"
ipaas:
  embedded_api_key: ""
  jwt_private_key: ""
  embed_base_url: ""
  api_base_url: ""

configure_logs: "true"
postgresql-ha:
  enabled: true
  postgresql:
    image:
      registry: docker.io
      repository: bitnami/postgresql-repmgr
      tag: 15.1.0-debian-11-r0
    replicaCount: 3
    containerPorts:
      postgresql: 5432
    podSecurityContext:
      enabled: false
      fsGroup: 1001
    containerSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: false

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    username: postgres
    password: "postgres"
    database: "forms-flow-ai"
    postgresPassword: "changeme"

    repmgrUsername: repmgr
    repmgrPassword: "changeme"
    repmgrDatabase: repmgr
    repmgrLogLevel: NOTICE
    repmgrConnectTimeout: 5
    repmgrReconnectAttempts: 2
    repmgrReconnectInterval: 3
    repmgrFenceOldPrimary: false
    repmgrChildNodesCheckInterval: 5
    repmgrChildNodesConnectedMinCount: 1
    repmgrChildNodesDisconnectTimeout: 30
    initdbScripts:
      init_script.sql: |
            CREATE DATABASE "forms-flow-admin";
            CREATE DATABASE "forms-flow-analytics";
            CREATE DATABASE "forms-flow-api";
            CREATE DATABASE "forms-flow-bpm";
            GRANT ALL PRIVILEGES ON DATABASE "forms-flow-admin" to postgres;
            GRANT ALL PRIVILEGES ON DATABASE "forms-flow-analytics" to postgres;
            GRANT ALL PRIVILEGES ON DATABASE "forms-flow-api" to postgres;
            GRANT ALL PRIVILEGES ON DATABASE "forms-flow-bpm" to postgres;
            set transaction read write;
            alter database "forms-flow-bpm" set default_transaction_read_only = off;
            alter database "forms-flow-api" set default_transaction_read_only = off;
            alter database "forms-flow-analytics" set default_transaction_read_only = off;
            alter database "forms-flow-admin" set default_transaction_read_only = off;
  pgpool:
    image:
      registry: docker.io
      repository: bitnami/pgpool
      tag: 4.3.3-debian-11-r28
      digest: ""
      pullPolicy: IfNotPresent
    replicaCount: 1
    podSecurityContext:
      enabled: false
      fsGroup: 1001
    containerSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    containerPorts:
      postgresql: 5432
    adminUsername: admin
    adminPassword: "changeme"
    service:
      type: ClusterIP
      ports:
        metrics: 9187
  persistence:
    enabled: true
    storageClass: ""
    mountPath: /bitnami/postgresql
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
    portName: postgresql
    nodePorts:
      postgresql: ""
redis-expoter:
  exporter:
    replica: 2
  redis:
    configMap:
      redis_conf: |
        cluster-enabled no
        cluster-require-full-coverage no
        cluster-node-timeout 15000
        cluster-config-file /data/nodes.conf
        cluster-migration-barrier 1
        appendonly no
        protected-mode no
        maxmemory 1449551462
