---
Domain: "apps.devops.aot-technologies.com"
websocket_encrypt_key: "FormsFlow.AI"
forms-flow-analytics:
  ingress: 
    enabled: true
    tls: 
      hosts: 
        - "apps.devops.aot-technologies.com"
forms-flow-bpm:
  ingress: 
    enabled: true 
    tls: 
      hosts: 
        - "apps.devops.aot-technologies.com"
  clientid: "forms-flow-bpm"
  clientsecret: "786001d6-68a8-4519-903c-bc5b5a870d68"
forms-flow-forms:
  ingress: 
    enabled: true # create an ingress for this component 
    tls: 
      hosts: 
        - "apps.devops.aot-technologies.com"
  admin:
    email: "me@defineme.com"
    password: "admin"
forms-flow-idm:
  keycloak:
    ingress:
      enabled: true
      hostname: "forms-flow-idm-formsflow-ai.apps.devops.aot-technologies.com"
  realm: forms-flow-ai
forms-flow-web:
  clientid: forms-flow-web
mongodb:
  arbiter: 
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
  architecture: replicaset
  auth:
    databases: 
      - formsflow 
    passwords:
      - mongodb
    usernames:
      - mongodb
  containerSecurityContext:
    enabled: false
  service:
    nameOverride: forms-flow-mongodb
    ports:
      mongodb: 27017
  replicaSetName: forms-flow-mongodb
  podSecurityContext:
    enabled: false


