application_name: keycloak
db_addr: keycloak-db
db_database: keycloakdb
db_password: keycloak
db_port: "5432"
db_user: keycloak
db_vendor: POSTGRES
hostname_http: '# TODO: must define a default value for .hostname_http'
keycloak_https: "true"
keycloak_password: '# TODO: must define a default value for .keycloak_password'
keycloak_user: '# TODO: must define a default value for .keycloak_user'
namespace: '# TODO: must define a default value for .namespace'
proxy_address_forwarding: "true"
