apiVersion: v2
name: forms-flow-web
description: forms-flow-web delivers progressive web application with React provided by formsflow.
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
version: v8.0.0
type: application
appVersion: "8.0.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x