---
Domain: #<DEFINE ME>
postgresql:
  host: forms-flow-ai-postgresql-ha-pgpool
  port: 5432

  username: 'postgres'
  password: 'postgres'

  externalSecret:
    name: 
    usernameKey: 'postgres'
    passwordKey: 'postgres'

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
  analytics: forms-flow-analytics #name of analytics component
  auth: forms-flow-ai-auth 
  

ingress:
  ingressClassName: ""
  annotations:
  enabled: true # create an ingress for this component 
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5000
  tls: true
  selfSigned: false
  extraTls:
   - {}
  path: /

image:
  registry: docker.io
  repository: formsflow/forms-flow-ai-admin
  tag: v5.2.0 #The image tag to pull from
