---
Domain: #<DEFINE ME>
replicas: 1
postgresql:
  databasename: "forms-flow-admin"
  username: "postgres"
  password: "postgres"
  port: 5432
  host: "forms-flow-ai-postgresql-ha-pgpool"
  url: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/${DATABASE_NAME}"
externalDatabase:
  existingDatabaseUrlKey: "" 
  existingSecretName: "" #name of the existing secret
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
  analytics: forms-flow-analytics #name of analytics component
  auth: forms-flow-ai-auth 
  

ingress:
  ingressClassName: ""
  annotations:
  enabled: true # create an ingress for this component 
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5000
  tls: true
  selfSigned: false
  extraTls:
   - {}
  path: /

image:
  registry: docker.io
  repository: formsflow/forms-flow-ai-admin
  tag: v6.0.0 #The image tag to pull from
elastic_search:
  enabled: false
