---
Domain: #<DEFINE_ME>
formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
ingress: 
  enabled: true # create an ingress for this component 
  port: 8080
resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
image:
  registry: docker.io
  repository: formsflow/forms-flow-web-container
  tag: 1.0.0
config_path: /usr/share/nginx/html/config/
