apiVersion: v1
id: {{ .Values.application_name }}-http
kind: Route
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    application: {{ .Values.application_name }}
  name: {{ .Values.application_name }}
spec:
  host: {{ .Values.hostname_http }}
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{ .Values.application_name }}
