apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: {{ .Values.application_name }}
  name: {{ .Values.application_name }}
spec:
  ports:
  - nodePort: 0
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.application_name }}
  sessionAffinity: None
  type: ClusterIP
