apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    app: {{ .Chart.Name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: MONGO_URL
              name: "{{ .Values.mongodb_secret_name }}"
        - name: BPM_API_BASE
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_API_URI
              name: "{{ .Values.formsflow_config_name }}"
        - name: BPM_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_ID
              name: "{{ .Values.formsflow_secret }}"
        - name: BPM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_SECRET
              name: "{{ .Values.formsflow_secret }}"
        - name: BPM_TOKEN_API
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_TOKEN_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.webapi_db_resource_name }}"
        - name: JWT_OIDC_ALGORITHMS
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_ALGORITHMS
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_AUDIENCE
          valueFrom:
            secretKeyRef:
              key: WEB_CLIENTID
              name: "{{ .Values.formsflow_secret }}"
        - name: JWT_OIDC_CACHING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CACHING_ENABLED
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_ISSUER
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_ISSUER
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_JWKS_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_JWKS_URI
              name: "{{ .Values.formsflow_config_name }}"
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CONFIG
              name: "{{ .Values.formsflow_config_name }}"
        - name: WEB_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: WEB_API_BASE_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: FORMSFLOW_API_CORS_ORIGINS
          value: '*'
        image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Chart.Name }}:{{ .Values.tag_name }}"
        name: "{{ .Chart.Name }}"
        ports:
        - containerPort: 5000
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
  test: false
