app_name: redash
cpu_limit: 400m
cpu_request: 300m
memory_limit: 512Mi
memory_request: 256Mi
redis_exporter_image: oliver006/redis_exporter
redis_exporter_name: redash-exporter
redis_exporter_tag: v1.14.0-alpine
redis_image: redis
redis_tag: latest
storage: 1Gi
storage_class: nfs-client
storage_size: 10Gi
