apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: 'postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}'
  labels:
    app: "{{ .Values.name }}-{{ .Values.tag_name }}"
    app-group: "{{ .Values.app_group }}"
    template: "{{ .Values.name }}-deploy"
  name: "{{ .Values.name }}-{{ .Values.tag_name }}"
spec:
  ports:
  - name: "{{ .Values.name }}-{{ .Values.tag_name }}"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: "{{ .Values.name }}-{{ .Values.tag_name }}"
  sessionAffinity: None
  type: ClusterIP
