apiVersion: v2
name: forms-flow-mcp
description: forms-flow-mcp is esigned to seamlessly integrate with forms-flow components, enabling efficient communication between MCP clients and backend services provided by formsflow.
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
version: v8.4.0
type: application
appVersion: "8.4.0"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.27.0
