apiVersion:  v1
kind:  ConfigMap
metadata: 
  name:  {{ include "common.names.fullname" . }}
  namespace:  {{ include "common.names.namespace" . | quote }}
  labels:  {{- include "common.labels.standard" ( dict "customLabels" .Values.server.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component:  forms-flow-analytics
  {{- if .Values.server.commonAnnotations }}
  annotations:  {{- include "common.tplvalues.render" ( dict "value" .Values.server.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data: 
  REDASH_HOST: "{{ tpl .Values.ingress.hostname . }}"
  REDASH_DATABASE_URL: "{{ tpl .Values.database.url . }}"
  REDASH_LOG_LEVEL: "INFO"
  DATABASE_PORT: "{{ .Values.database.port }}"

