apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}-server"
  name: "{{ .Chart.Name }}-server"
spec:
  replicas: 1
  selector:
    app: "{{ .Chart.Name }}-server"
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      post:
        execNewPod:
          containerName: "{{ .Chart.Name }}-server"
          command:
          - /bin/sh
          - -c
          - python ./manage.py database create_tables
        failurePolicy: ignore
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-server"
      name: "{{ .Chart.Name }}-server"
    spec:
      containers:
      - args:
        - server
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: "{{ .Chart.Name }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: "{{ .Chart.Name }}"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: "{{ .Chart.Name }}"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: "{{ .Chart.Name }}"
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: "{{ .Chart.Name }}"
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: "{{ .Chart.Name }}"
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Chart.Name }}"
        - name: REDASH_WEB_WORKERS
          value: "4"
        - name: GUNICORN_CMD_ARGS
          value: "--timeout 300"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.image_tag }}"
        name: "{{ .Chart.Name }}-server"
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ .Chart.Name }}-server"
      from:
        kind: ImageStreamTag
        name: "{{ .Values.imagestream_name }}:{{ .Values.image_tag }}"
        namespace: "{{ .Release.Namespace }}-tools"
    type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}-adhoc-worker"
  name: "{{ .Chart.Name }}-adhoc-worker"
spec:
  replicas: 1
  selector:
    app: "{{ .Chart.Name }}-adhoc-worker"
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-adhoc-worker"
    spec:
      containers:
      - args:
        - worker
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: "{{ .Chart.Name }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: "{{ .Chart.Name }}"
        - name: QUEUES
          value: "queries"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: "{{ .Chart.Name }}"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: "{{ .Chart.Name }}"
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: "{{ .Chart.Name }}"
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: "{{ .Chart.Name }}"
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Chart.Name }}"
        - name: WORKERS_COUNT
          value: "2"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.image_tag }}"
        name: "{{ .Chart.Name }}-adhoc-worker"
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ .Chart.Name }}-adhoc-worker"
      from:
        kind: ImageStreamTag
        name: "{{ .Values.imagestream_name }}:{{ .Values.image_tag }}"
        namespace: "{{ .Release.Namespace }}-tools"
    type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}-scheduled-worker"
  name: "{{ .Chart.Name }}-scheduled-worker"
spec:
  replicas: 1
  selector:
    app: "{{ .Chart.Name }}-scheduled-worker"
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-scheduled-worker"
    spec:
      containers:
      - args:
        - worker
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: "{{ .Chart.Name }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: "{{ .Chart.Name }}"
        - name: QUEUES
          value: "scheduled_queries,schemas"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: "{{ .Chart.Name }}"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: "{{ .Chart.Name }}"
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: "{{ .Chart.Name }}"
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: "{{ .Chart.Name }}"
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Chart.Name }}"
        - name: WORKERS_COUNT
          value: "1"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.image_tag }}"
        name: "{{ .Chart.Name }}-scheduled-worker"
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ .Chart.Name }}-scheduled-worker"
      from:
        kind: ImageStreamTag
        name: "{{ .Values.imagestream_name }}:{{ .Values.image_tag }}"
        namespace: "{{ .Release.Namespace }}-tools"
    type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}-scheduler"
  name: "{{ .Chart.Name }}-scheduler"
spec:
  replicas: 1
  selector:
    app: "{{ .Chart.Name }}-scheduler"
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-scheduler"
    spec:
      containers:
      - args:
        - scheduler
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: "{{ .Chart.Name }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: "{{ .Chart.Name }}"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: "{{ .Chart.Name }}"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: "{{ .Chart.Name }}"
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: "{{ .Chart.Name }}"
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: "{{ .Chart.Name }}"
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Chart.Name }}"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.image_tag }}"
        name: "{{ .Chart.Name }}-scheduler"
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ .Chart.Name }}-scheduler"
      from:
        kind: ImageStreamTag
        name: "{{ .Values.imagestream_name }}:{{ .Values.image_tag }}"
        namespace: "{{ .Release.Namespace }}-tools"
    type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ .Chart.Name }}-worker"
  name: "{{ .Chart.Name }}-worker"
spec:
  replicas: 1
  selector:
    app: "{{ .Chart.Name }}-worker"
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-worker"
    spec:
      containers:
      - args:
        - worker
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST_AUTH_METHOD
              name: "{{ .Chart.Name }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: PYTHONUNBUFFERED
          valueFrom:
            secretKeyRef:
              key: PYTHONUNBUFFERED
              name: "{{ .Chart.Name }}"
        - name: QUEUES
          value: "periodic emails default"
        - name: REDASH_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: REDASH_COOKIE_SECRET
              name: "{{ .Chart.Name }}"
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: REDASH_HOST
          valueFrom:
            secretKeyRef:
              key: REDASH_HOST
              name: "{{ .Chart.Name }}"
        - name: REDASH_LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: REDASH_LOG_LEVEL
              name: "{{ .Chart.Name }}"
        - name: REDASH_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDASH_REDIS_URL
              name: "{{ .Chart.Name }}"
        - name: REDASH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REDASH_SECRET_KEY
              name: "{{ .Chart.Name }}"
        - name: WORKERS_COUNT
          value: "1"
        image: ' '
        name: "{{ .Chart.Name }}-worker"
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ .Chart.Name }}-worker"
      from:
        kind: ImageStreamTag
        name: "{{ .Values.imagestream_name }}:{{ .Values.image_tag }}"
        namespace: "{{ .Release.Namespace }}-tools"
    type: ImageChange
