apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 60m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: {{ .Values.sslcertificate.issuer }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: upgrade-insecure-requests";
      more_set_headers 'Strict-Transport-Security: max-age=63072000; includeSubDomains; preload';
spec:
  tls:
    - hosts:
      - {{ .Values.Domain }}
      secretName: {{ .Values.sslcertificate.secretName }}
  rules:
    - host: {{ .Values.Domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Chart.Name }}
                 port:
                    number: 5000