apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forms-flow-ai-postgresql-ha-pgpool
  name: forms-flow-ai-postgresql-ha-pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forms-flow-ai-postgresql-ha-pgpool
  template:
    metadata:
      labels:
        app: forms-flow-ai-postgresql-ha-pgpool
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: "forms-flow-analytics"
---
apiVersion: v1
kind: Service
metadata:
  name: forms-flow-ai-postgresql-ha-pgpool-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: forms-flow-ai-postgresql-ha-pgpool

