apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redash.fullname" . }}-nginx-config
  labels:
    {{- include "redash.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      server {
        client_max_body_size {{ .Values.maxSizePayload }};
        listen {{ .Values.ingress.port }};
        location /redash/ {
          sub_filter ="/" ="/redash/";
          sub_filter ="/static/ ="/redash/static/;
          sub_filter ="/api/ ="/redash/api/;
          sub_filter ="/static/images/redash_icon_small.png ="/redash/static/images/redash_icon_small.png;
          sub_filter url(/static/fonts) url(/redash/static/fonts);
          sub_filter_once off;
          sub_filter_types application/javascript text/css text/xml text/javascript application/json text/plain;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          sub_filter "http://{{ .Values.ingress.subFilterHost }}/" "https://{{ .Values.ingress.subFilterHost }}/";         
          proxy_set_header SCRIPT_NAME /redash;
          
          proxy_pass http://localhost:{{ .Values.server.httpPort }};
        }
        location = /setup {
          return 301 /redash/setup;
        } 
        
      }
    }
    pid /tmp/nginx.pid;