apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  host: {{ tpl .Values.analytics_url . }}
  path: /
  port:
    targetPort: "7000"
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
  wildcardPolicy: None
