---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-scheduler" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.scheduler.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-analytics-scheduler
  {{- if .Values.scheduler.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  strategy: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.updateStrategy "context" $ ) | nindent 4 }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.scheduler.podLabels .Values.scheduler.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: forms-flow-analytics-scheduler
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: forms-flow-analytics-scheduler
      annotations:
        {{- if not .Values.scheduler.existingSecret  }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
        {{- if (include "forms-flow-analytics.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.scheduler.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "forms-flow-analytics.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "forms-flow-analytics.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.scheduler.automountServiceAccountToken }}
      {{- if .Values.scheduler.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.scheduler.podAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.scheduler.podAntiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.scheduler.nodeAffinityPreset.type "key" .Values.scheduler.nodeAffinityPreset.key "values" .Values.scheduler.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.scheduler.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.schedulerName }}
      schedulerName: {{ .Values.scheduler.schedulerName }}
      {{- end }}
      {{- if .Values.scheduler.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.priorityClassName }}
      priorityClassName: {{ .Values.scheduler.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.scheduler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.scheduler.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.scheduler.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.scheduler.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
      - name: forms-flow-analytics-scheduler
        image: {{ include "forms-flow-analytics.image" . }}
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy | quote }}
        {{- if .Values.scheduler.containerSecurityContext.enabled }}
        securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.scheduler.containerSecurityContext "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.scheduler.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.diagnosticMode.command "context" $) | nindent 12 }}
        {{- else if .Values.scheduler.command }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.command "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.scheduler.diagnosticMode.enabled }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.diagnosticMode.args "context" $) | nindent 12 }}
        {{- else if .Values.scheduler.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.args "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.scheduler.lifecycleHooks }}
        lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.lifecycleHooks "context" $) | nindent 12 }}
        {{- end }}
        env:
        {{- if .Values.externalDatabase.existingDatabaseUrlKey }}
        - name: REDASH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: {{ .Values.externalDatabase.existingDatabaseUrlKey }}
              name: "{{ .Values.externalDatabase.existingSecretName }}"
        {{- end }}
        {{- if not .Values.externalDatabase.existingDatabaseUrlKey }}
        - name: REDASH_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDASH_DATABASE_URL
              name: "{{ .Chart.Name }}"
        {{- end }}
        {{- if .Values.scheduler.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.extraEnvVars "context" $) | nindent 12 }}
        {{- end }}
        envFrom:
        {{- if .Values.scheduler.extraEnvVarsCM }}
        - configMapRef:
            name: {{ include "common.tplvalues.render" (dict "value" .Values.scheduler.extraEnvVarsCM "context" $) }}
        {{- else}}
        - configMapRef:
            name: {{ include "common.names.fullname" . }}
        {{- end }}
        {{- if .Values.scheduler.extraEnvVarsSecret }}
        - secretRef:
            name: {{ include "common.tplvalues.render" (dict "value" .Values.scheduler.extraEnvVarsSecret "context" $) }}
        {{- else}}
        - secretRef:
            name: {{ include "common.names.fullname" . }}
        {{- end }}
        {{- if .Values.scheduler.resources }}
        resources: {{- toYaml .Values.scheduler.resources | nindent 12 }}
        {{- else if ne .Values.scheduler.resourcesPreset "none" }}
        resources: {{- include "common.resources.preset" (dict "type" .Values.scheduler.resourcesPreset) | nindent 12 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.scheduler.containerPorts.http }}
          protocol: TCP
        volumeMounts:
          {{- if .Values.scheduler.extraVolumeMounts }}
          {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.extraVolumeMounts "context" $ ) | nindent 12 }}
          {{- end }}
        {{- if .Values.scheduler.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.scheduler.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
      restartPolicy: Always