{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.server.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-analytics
  {{- if or .Values.server.annotations .Values.server.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.server.annotations .Values.server.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  PYTHONUNBUFFERED: "0"
  REDASH_COOKIE_SECRET: redash-selfhosted
  REDASH_REDIS_URL: "redis://redis-exporter:6379/0" # url of the redis database to connect to
  REDASH_SECRET_KEY: redash-selfhosted
  REDASH_MULTI_ORG: "{{ .Values.redash.multiorg }}"
  DATABASE_USERNAME: "{{ .Values.database.username }}"
  DATABASE_PASSWORD: "{{ .Values.database.password }}"
  DATABASE_NAME: "{{ .Values.database.dbName }}"
  DATABASE_HOST: "{{ .Values.database.servicename }}"
{{- end }}