apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: "{{ .Values.ingress.port }}"
    port: {{ .Values.ingress.port }}
    targetPort: {{ .Values.ingress.port }}
  selector:
    app: {{ .Chart.Name }}-server
