{{ range $workerName, $config := .Values.workers -}}
{{- $workerConfig := mergeOverwrite (deepCopy $.Values.worker) $config }}
{{- $context := mergeOverwrite (deepCopy $) (dict "workerName" $workerName)}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forms-flow-analytics.worker.fullname" $context }}
  labels: {{ include "forms-flow-analytics.labels" $context | nindent 4 }}
    app.kubernetes.io/component: forms-flow-analytics-worker
spec:
  replicas: {{ $workerConfig.replicaCount }}
  selector: 
    matchLabels: {{ include "forms-flow-analytics.selectorLabels" $context | nindent 6 }}
      app.kubernetes.io/component: forms-flow-analytics-worker
  template:
    metadata:
      labels: {{ include "forms-flow-analytics.selectorLabels" $context | nindent 8 }}
        app.kubernetes.io/component: forms-flow-analytics-worker
      {{- with $workerConfig.podLabels }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.podAnnotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
      - name: forms-flow-ai-auth
      serviceAccountName: {{ include "forms-flow-analytics.serviceAccountName" $context }}
      securityContext: {{ toYaml $workerConfig.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "forms-flow-analytics.name" $context }}-{{ $workerName }}-worker
        image: {{ $.Values.worker.image.registry }}/{{ $.Values.worker.image.repository }}:{{ $.Values.worker.image.tag }}
        imagePullPolicy: {{ $.Values.worker.image.pullPolicy }}
        securityContext: {{ toYaml $workerConfig.securityContext | nindent 10 }}
        args:
          - worker
        env:
        {{- $env := mergeOverwrite (deepCopy $) (dict "Values" (dict "env" $workerConfig.env)) -}}
        {{- include "forms-flow-analytics.worker.env" $env | nindent 10 }}
        {{- with (include "forms-flow-analytics.worker.envFrom" $) }}
        envFrom: {{ . | nindent 10 }}
        {{- end }}
        {{- with $workerConfig.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- $volumeMounts :=  $workerConfig.extraVolumeMounts }}
        {{- with $volumeMounts }}
        volumeMounts: {{ toYaml . | nindent 8 }}
        {{- end -}}
      {{- $volumes := $workerConfig.extraVolumes }}
      {{- with $volumes }}
      volumes:{{ toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: Always
{{- end }}