---
keycloak:
  extraVolumes: |
    - name: forms-flow-idm 
      configMap:
        name: forms-flow-idm

  extraVolumeMounts: |
    - name: forms-flow-idm
      mountPath: "/realm/"
      readOnly: true

  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json

  podSecurityContext: {"fsGroup":1000650000}
