---
keycloak:
  extraVolumes: |
    - name: "{{ .Chart.Name }}-realm"
      configMap:
        name: "{{ .Chart.Name }}-realm"

  extraVolumeMounts: |
    - name: "{{ .Chart.Name }}-realm"
      mountPath: "/realm/"
      readOnly: true

  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: "/realm/realm.json"
    
  # Docker image used to check Postgresql readiness at startup 
  pgchecker:
    securityContext:
      runAsUser: 1000650000
      runAsGroup: 1000650000
      runAsNonRoot: true

  podSecurityContext: 
    fsGroup: 1000650000
  
## "auto" is especially useful for OpenShift which has scc with dynamic userids (and 0 is not allowed).
## You may want to use this volumePermissions.securityContext.runAsUser="auto" in combination with
## pod securityContext.enabled=false and shmVolume.chmod.enabled=false
  postgresql:
    securityContext:
      enabled: false 
    shmVolume:
      chmod:
        enabled: false
    ## @param volumePermissions.enabled Enable init container that changes volume permissions in the data directory (for cases where the default k8s `runAsUser` and `fsUser` values do not work)
    volumePermissions:
      enabled: true
      securityContext:
        runAsUser: "auto"
  
  route:
    enabled: true
    path:  /
    labels: {"app":"forms-flow-idm"}
    host: "formsflow.idm.apps.devops.aot-technologies.com"
    tls:
      enabled: true
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
  
  # SecurityContext for the Keycloak container
  securityContext:
    runAsUser: 1000650000
    runAsNonRoot: true
name: forms-flow-idm
