---
keycloak:
  extraVolumes: |
    - name: forms-flow-idm 
      configMap:
        name: forms-flow-idm

  extraVolumeMounts: |
    - name: forms-flow-idm
      mountPath: "/realm/"
      readOnly: true

  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json

  podSecurityContext: {"fsGroup":1000650000}

  route.enabled: true
  route.path:  /
  route.labels: {"app":"forms-flow-idm"}
  route.host: "formsflow.idm.apps.devops.aot-technologies.com"
  route.tls.enabled: true
  route.tls.insecureEdgeTerminationPolicy: Redirect
  route.tls.termination: edge
