---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .Values.name }}"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "{{ .Values.redis_image }}"
    name: "{{ .Chart.Name }}"
    referencePolicy:
      type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .Values.redis_exporter_name }}"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "registry.hub.docker.com/{{ .Values.redis_exporter_image }}"
    name: "{{ .Chart.Name }}"
    referencePolicy:
      type: Local
