cpu_limit: 750m
cpu_request: 100m
forms_url: formio.apps.devops.aot-technologies.com
formsflow_secret: forms-flow-ai
memory_limit: 2Gi
memory_request: 100Mi
tag_name: latest
mongodb_secret_name: formio-mongodb
source_repository_ref: master 
source_repository_url: https://github.com/AOT-Technologies/forms-flow-ai
source_context_dir: /forms-flow-forms
