apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  host: {{ .Values.forms_url }}
  port:
    targetPort: "3001"
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
