apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: forms-flow-web
  name: forms-flow-web
spec:
  output:
    to:
      kind: ImageStreamTag
      name: forms-flow-web:latest
  resources:
    limits:
      cpu: "1"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  runPolicy: Serial
  source:
    contextDir: {{ .Values.source_context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
