apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Chart.Name }}
spec:
  host: {{ .Values.web_url }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
  wildcardPolicy: None
