apiVersion: v1
kind: Service
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.app_name }}
status:
  loadBalancer: {}
