---
apiVersion: v2
dependencies:
  - name: forms-flow-webapi-postgresql
    version: v0.1.0
    repository: "https://cberg-aot.github.io/helm-charts/"
name: forms-flow-webapi
tags: forms-flow-webapi
version: v0.1.0
