apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.redash_image_name }}:{{ .Values.redash_image_tag }}"
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: "1"
      memory: 4Gi
  source:
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
