apiVersion: v1
kind: Service
labels:
  app: {{ .Values.name }}
metadata:
  name: {{ .Values.name }}
name: {{ .Values.name }}
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 5000
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
