apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 5000
  selector:
    app: {{ .Values.name }}
status:
  loadBalancer: {}
