apiVersion: v2
name: forms-flow-bpm
description: forms-flow-bpm is a component which leverages Camunda for workflow and decision automation and its provided by formsflow.
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
version: v8.1.0
type: application
appVersion: "8.1.0"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.27.0
