Domain: #<DEFINE_ME>
camunda:
  analytics:
    database: forms-flow-analytics
  auth:
    enabled: true
    revokeCheck: auto
  database:
    name: forms-flow-bpm
    port: 5432
  historyLevel: auto
  securityOrigin: '*'
  logLevel: INFO
  formBuilder:
    password: demo # CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
    username: demo # CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
  hikari:
    timeout:
      connection: 30000 #CAMUNDA_HIKARI_CONNECTION_TIMEOUT
      idle: 600000 #CAMUNDA_HIKARI_IDLE_TIMEOUT
      valid: 5000 #CAMUNDA_HIKARI_VALID_TIMEOUT
    poolsize:
      max: 10 #CAMUNDA_HIKARI_MAX_POOLSIZE
  jdbc:
    driver: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://${CAMUNDA_DATABASE_SERVICE_NAME}:${CAMUNDA_DATABASE_PORT}/${CAMUNDA_DATABASE_NAME}"
  websocket:
    messageType: TASK_EVENT #WEBSOCKET_MESSAGE_TYPE
    securityOrigin:   #WEBSOCKET_SECURITY_ORIGIN
  externalDatabase:
    existingDatabaseHostKey: ""
    existingDatabasePortKey: ""
    existingDatabaseNameKey: ""
    existingSecretName: "" #name of the existing secret

image:
  registry: docker.io
  repository: formsflow/forms-flow-bpm
  tag: v6.0.0 #The image tag to pull from
formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret 
  auth: forms-flow-ai-auth
ingress:
  ingressClassName: ""
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "session"
  enabled: true # create an ingress for this component
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 8080
  tls: true
  selfSigned: false
  extraTls:
   - {}
mail:
  protocol: smtp
  from: "<DEFINE_ME>"
  password: "<DEFINE_ME>"
  user: "<DEFINE_ME>"
  alias: DoNotReply
  folder: INBOX
  smtp:
    auth: true
    port: 5432
    server: "<DEFINE_ME>"
    socketFactory:
      port: 465
      class: javax.net.ssl.SSLSocketFactory
    ssl:
      enable: false
  store:
    protocol: imaps
  imaps:
    host: imap.gmail.com
    port: 993
    timeout: 1000
  attachment:
    download: true
    path: attachments

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
hpa:
  enabled: false
  CpuAverageUtilization: 60
  maxReplicas: 3
elastic_search:
  enabled: false
waitFor: "${CAMUNDA_DATABASE_SERVICE_NAME}:${CAMUNDA_DATABASE_PORT}"
