apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: forms-flow-forms
  name: forms-flow-forms
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Chart.Name }}:{{ .Values.tag_name }}"
  resources:
    limits:
      cpu: "{{ .Values.cpu_limit }}"
      memory: "{{ .Values.memory_limit }}"
    requests:
      cpu: "{{ .Values.cpu_request }}"
      memory:"{{ .Values.memory_request }}"
  source:
    contextDir: {{ .Values.source_context_dir }}
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
