---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      {{- if .Values.elastic_search.enabled }} 
      - name: filebeat-api
        image: docker.elastic.co/beats/filebeat:7.14.0
        env:
          - name: ELASTIC_SERVER
            valueFrom:
              configMapKeyRef:
                key: ELASTIC_SERVER
                name: "{{ .Values.formsflow.configmap }}"
        volumeMounts:
        - name: api-logs
          mountPath: /forms-flow-api/app/logs
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: api-filebeat
      {{- end}}
      - env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              key: MONGODB_URI
              name: "{{ .Values.formsflow.configmap }}"
        - name: BPM_API_URL
          valueFrom:
            configMapKeyRef:
              key: BPM_API_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: BPM_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_CLIENTID
              name: "{{ .Values.formsflow.secret }}"
        - name: BPM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_CLIENTSECRET
              name: "{{ .Values.formsflow.secret }}"
        - name: BPM_TOKEN_API
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_TOKEN_URL
              name: "{{ .Values.formsflow.configmap }}"
        {{- if .Values.ExternalDatabase.ExistingDatabaseNameKey }}
        - name: FORMSFLOW_API_DB_NAME
          valueFrom:
            secretKeyRef:
              key: {{ .Values.ExternalDatabase.ExistingDatabaseNameKey }}
              name: "{{ .Values.ExternalDatabase.ExistingSecretName }}"
        {{- end }}
        {{- if not .Values.ExternalDatabase.ExistingDatabaseNameKey }}
        - name: FORMSFLOW_API_DB_NAME
          valueFrom:
            secretKeyRef:
              key: FORMSFLOW_API_DB_NAME
              name: "{{ .Chart.Name }}"
        {{- end }}
        {{- if .Values.ExternalDatabase.ExistingDatabasePasswordKey }}
        - name: FORMSFLOW_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: {{ .Values.ExternalDatabase.ExistingDatabasePasswordKey }}
              name: "{{ .Values.ExternalDatabase.ExistingSecretName }}"
        {{- end }}
        {{- if not .Values.ExternalDatabase.ExistingDatabasePasswordKey }}
        - name: FORMSFLOW_API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: FORMSFLOW_API_DB_PASSWORD
              name: "{{ .Chart.Name }}"
        {{- end }}
        {{- if .Values.ExternalDatabase.ExistingDatabaseUserNameKey }}
        - name: FORMSFLOW_API_DB_USER
          valueFrom:
            secretKeyRef:
              key: {{ .Values.ExternalDatabase.ExistingDatabaseUserNameKey }}
              name: "{{ .Values.ExternalDatabase.ExistingSecretName }}"
        {{- end }}
        {{- if not .Values.ExternalDatabase.ExistingDatabaseUserNameKey }}
        - name: FORMSFLOW_API_DB_USER
          valueFrom:
            secretKeyRef:
              key: FORMSFLOW_API_DB_USER
              name: "{{ .Chart.Name }}"
        {{- end }}
        - name: FORMSFLOW_API_PORT
          valueFrom:
            configMapKeyRef:
              key: FORMSFLOW_API_PORT
              name: "{{ .Chart.Name }}"
        - name: FORMSFLOW_API_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: FORMSFLOW_API_HOSTNAME
              name: "{{ .Chart.Name }}"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: "{{ .Chart.Name }}"
        - name: JWT_OIDC_ALGORITHMS
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_ALGORITHMS
              name: "{{ .Values.formsflow.configmap }}"
        - name: JWT_OIDC_AUDIENCE
          valueFrom:
            secretKeyRef:
              key: WEB_CLIENTID
              name: "{{ .Values.formsflow.secret }}"
        - name: JWT_OIDC_CACHING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CACHING_ENABLED
              name: "{{ .Values.formsflow.configmap }}"
        - name: JWT_OIDC_ISSUER
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_ISSUER
              name: "{{ .Values.formsflow.configmap }}"
        - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT
              name: "{{ .Values.formsflow.configmap }}"
        - name: JWT_OIDC_JWKS_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_JWKS_URI
              name: "{{ .Values.formsflow.configmap }}"
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_JWT_OIDC_CONFIG
              name: "{{ .Values.formsflow.configmap }}"
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: WEB_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: WEB_API_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: KEYCLOAK_URL_REALM
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL_REALM
              name: "{{ .Values.formsflow.configmap }}"
        - name: INSIGHT_API_URL
          valueFrom:
            configMapKeyRef:
              key: INSIGHT_API_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: INSIGHT_API_KEY
          valueFrom:
            secretKeyRef:
              key: INSIGHT_API_KEY
              name: "{{ .Values.formsflow.secret }}"
        - name: KEYCLOAK_ENABLE_CLIENT_AUTH
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ENABLE_CLIENT_AUTH
              name: "{{ .Values.formsflow.configmap }}"
        - name: MULTI_TENANCY_ENABLED
          valueFrom:
            configMapKeyRef:
              key: MULTI_TENANCY_ENABLED
              name: "{{ .Values.formsflow.configmap }}"
        - name: FORMIO_URL
          valueFrom:
            configMapKeyRef:
              key: FORMIO_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: FORMIO_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_EMAIL
              name: "{{ .Values.formsflow.secret }}"
        - name: FORMIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_PASSWORD
              name: "{{ .Values.formsflow.secret }}"
        - name: FORMIO_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: FORMIO_JWT_SECRET
              name: "{{ .Values.formsflow.secret }}"
        - name: IPAAS_EMBEDDED_API_KEY
          valueFrom:
            secretKeyRef:
              key: IPAAS_EMBEDDED_API_KEY
              name: "{{ .Values.formsflow.secret }}"
        - name: IPAAS_JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: IPAAS_JWT_PRIVATE_KEY
              name: "{{ .Values.formsflow.secret }}"
        - name: IPAAS_EMBED_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: IPAAS_EMBED_BASE_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: IPAAS_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: IPAAS_API_BASE_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: "{{ .Values.formsflow.configmap }}"
        - name: FORMSFLOW_API_CORS_ORIGINS
          value: '*'
        - name: CONFIGURE_LOGS
          valueFrom:
            configMapKeyRef:
              key: CONFIGURE_LOGS
              name: "{{ .Values.formsflow.configmap }}"
        - name: KEYCLOAK_URL_HTTP_RELATIVE_PATH
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL_HTTP_RELATIVE_PATH
              name: "{{ .Values.formsflow.configmap }}"
        
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: "{{ .Chart.Name }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ingress.port }}
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        stdin: true
        tty: true
     {{- if .Values.elastic_search.enabled }} 
        volumeMounts:
        - name: api-logs
          mountPath: /forms-flow-api/app/logs
      volumes:
      - name: api-logs
      - name: api-filebeat
        configMap:
          name: "{{ .Chart.Name }}-fb-config"
     {{- end}}
      restartPolicy: Always
      imagePullSecrets:
      - name: "{{ .Values.formsflow.auth }}"
