apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 60m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: {{ .Values.sslcertificate.issuer }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.org/redirect-to-https: "yes"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: upgrade-insecure-requests";
      more_set_headers 'Strict-Transport-Security: max-age=63072000; includeSubDomains; preload';
      proxy_set_header Accept-Encoding "";
      sub_filter '/swagger' '/api/swagger';
      sub_filter_once off;
      sub_filter_types application/javascript text/xml text/css text/javascript application/json text/plain text/javascript;
spec:
  tls:
    - hosts:
      - {{ .Values.Domain }}
      secretName: {{ .Values.sslcertificate.secretName }}
  rules:
    - host: {{ .Values.Domain }}
      http:
        paths:
          - path: /api()(.*)
            pathType: Prefix
            backend:
              service:
                 name: forms-flow-api
                 port:
                    number: 5000