{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-api
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  FORMSFLOW_API_DB_USER: {{ .Values.database.username }}
  FORMSFLOW_API_DB_PASSWORD: {{ .Values.database.password }}
  FORMSFLOW_API_DB_NAME: {{ .Values.database.dbName }}
  FORMSFLOW_API_HOSTNAME: {{ .Values.database.dbName }}
{{- end }}