---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  FORMSFLOW_API_DB_USER: {{ .Values.database.username }}
  FORMSFLOW_API_DB_PASSWORD: {{ .Values.database.password }}
  FORMSFLOW_API_DB_NAME: {{ .Values.database.dbName }}
  FORMSFLOW_API_HOSTNAME: {{ .Values.database.dbName }}

