apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.app_group }}
    name: {{ .Values.mongodb_service_name }}
  name: {{ .Values.mongodb_service_name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app_group }}
  serviceName: {{ .Values.mongodb_service_name }}-internal
  template:
    metadata:
      labels:
        app: {{ .Values.app_group }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - {{ .Values.mongodb_service_name }}
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - run-mongod-replication
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              key: mongo-oplog-url
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGODB_REPLICA_NAME
          valueFrom:
            secretKeyRef:
              key: replica-name
              name: {{ .Values.mongodb_secret_name }}
        - name: MONGODB_KEYFILE_VALUE
          value: {{ .Values.mongodb_keyfile_value }}
        - name: MONGODB_SERVICE_NAME
          value: {{ .Values.mongodb_service_name }}-internal
        image: {{ .Values.mongodb_image }}:{{ .Values.mongodb_image_tag }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  if [ ! -f /var/lib/mongodb/data/db/admin-user.lock ]; then
                    sleep 5;
                    touch /var/lib/mongodb/data/db/admin-user.lock
                    if [ "$HOSTNAME" = "mongo-0" ]; then
                      mongo --eval 'db = db.getSiblingDB("admin"); db.createUser({ user: "admin", pwd: "password", roles: [{ role: "root", db: "admin" }]});';
                    fi;
                    mongod --shutdown;
                  fi;
        name: mongo-container
        ports:
        - containerPort: 27017
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/initialized
        resources:
          limits:
            cpu: {{ .Values.cpu_limit }}
            memory: {{ .Values.memory_limit }}
          requests:
            cpu: {{ .Values.cpu_request }}
            memory: {{ .Values.memory_request }}
        volumeMounts:
        - mountPath: /var/lib/mongodb/data
          name: mongo-data
  volumeClaimTemplates:
  - metadata:
      labels:
        app: {{ .Values.app_group }}
        name: {{ .Values.mongodb_service_name }}
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.volume_capacity }}
      storageClassName: {{ .Values.sc_mongo }}
