apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_group }}
    name: {{ .Values.mongodb_service_name }}
  name: {{ .Values.mongodb_service_name }}
spec:
  ports:
  - name: mongodb
    port: 27017
  selector:
    name: {{ .Values.mongodb_service_name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ .Values.app_group }}
    name: {{ .Values.mongodb_service_name }}
  name: {{ .Values.mongodb_service_name }}-internal
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    name: {{ .Values.mongodb_service_name }}
