apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: 'postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}'
  labels:
    app: "{{ .Chart.Name }}"
    app-group: "{{ .Values.app_group }}"
  name: "{{ .Chart.Name }}"
spec:
  ports:
  - name: "{{ .Chart.Name }}"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: "{{ .Chart.Name }}"
  sessionAffinity: None
  type: ClusterIP
