---
Domain: #<DEFINE_ME>
replicas: 1
database:
  username: "postgres"
  password: "postgres"
  dbName: "forms-flow-api"
  host: "forms-flow-ai-postgresql-ha-pgpool"
  port: 5432
  url: "postgresql://{{.Values.database.username}}:{{.Values.database.password}}@{{.Values.database.host}}:{{.Values.database.port}}/{{.Chart.Name}}"
ExternalDatabase:
  ExistingDatabaseNameKey: ""
  ExistingDatabaseUserNameKey: ""
  ExistingDatabasePasswordKey: ""
  ExistingDatabaseHostKey: ""
  ExistingSecretName: "" #name of the existing secret

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
  auth: forms-flow-ai-auth 
ingress:
  ingressClassName: ""
  annotations:

  enabled: true # create an ingress for this component
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5000
  tls: true
  selfSigned: false
  extraTls:
    - {}
image:
  registry: docker.io
  repository: formsflow/forms-flow-webapi
  tag: v6.0.2 #The image tag to pull from
hpa:
  enabled: false
  CpuAverageUtilization: 80
  maxReplicas: 3
elastic_search:
  enabled: false