---
Domain: #<DEFINE_ME>

postgresql:
  host: forms-flow-ai-postgresql-ha-pgpool
  port: 5432

  database: "forms-flow-api"

  username: postgres
  password: postgres

  externalSecret:
    name: 
    usernameKey: username
    passwordKey: password

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

formsflow:
  configmap: forms-flow-ai # name of formsflow.ai configmap
  secret: forms-flow-ai #name of formsflow.ai secret
  auth: forms-flow-ai-auth 

ingress:
  ingressClassName: ""
  annotations:

  enabled: true # create an ingress for this component
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 5000
  tls: true
  selfSigned: false
  extraTls:
    - {}

image:
  registry: docker.io
  repository: formsflow/forms-flow-webapi
  tag: v5.2.0 #The image tag to pull from
