{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-mcp
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  FORMSFLOW_BEARER_TOKEN: "{{ .Values.formsflowBearerToken }}"
  MCP_PASSWORD: "{{ .Values.mcpPassword }}"
  MCP_USERNAME: "{{ .Values.mcpUsername }}"
  MCP_ROPC_CLIENT_ID: "{{ .Values.mcpRopcClientId }}"
  MCP_ROPC_CLIENT_SECRET: "{{ .Values.mcpRopcClientSecret }}" 
{{- end }}