apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-ai
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
    DATABASE_NAME: {{ ternary (tpl .Values.formsflowdb.postgresql.database .) "<DEFINE_ME>" .Values.formsflowdb.postgresql.enabled | quote }}
    DATABASE_PORT: {{ ternary .Values.formsflowdb.service.ports.postgresql "<DEFINE_ME>" .Values.formsflowdb.postgresql.enabled | quote }}
    DATABASE_SERVICE_NAME: {{ ternary (tpl .Values.formsflowdb.postgresql.fullnameOverride .) "<DEFINE_ME>" .Values.formsflowdb.postgresql.enabled | quote }}
    BPM_API_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/camunda
    BPM_API_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-bpm" "service" "name") . }}:{{ tpl (index .Values "forms-flow-bpm" "service" "port") . }}/camunda
    KEYCLOAK_JWT_OIDC_ALGORITHMS: "RS256"
    KEYCLOAK_JWT_OIDC_CACHING_ENABLED: "True"
    KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
    KEYCLOAK_JWT_OIDC_CONFIG: https://{{ tpl (index .Values "forms-flow-idm" "keycloak" "ingress" "hostname" ) .}}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/.well-known/openid-configuration
    KEYCLOAK_JWT_OIDC_ISSUER: https://{{ tpl (index .Values "forms-flow-idm" "keycloak" "ingress" "hostname") . }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}
    KEYCLOAK_JWT_OIDC_JWKS_URI: https://{{ tpl (index .Values "forms-flow-idm" "keycloak" "ingress" "hostname") . }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/certs
    KEYCLOAK_TOKEN_URL: https://{{ tpl (index .Values "forms-flow-idm" "keycloak" "ingress" "hostname") . }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/token
    KEYCLOAK_URL: https://{{ tpl (index .Values "forms-flow-idm" "keycloak" "ingress" "hostname") . }}
    KEYCLOAK_URL_REALM: {{ index .Values "forms-flow-idm" "realm" }}
    FORMIO_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/formio
    FORMIO_DOMAIN: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/formio
    FORMIO_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-forms" "service" "name") . }}:{{ tpl (index .Values "forms-flow-forms" "service" "port") . }}
    WEB_API_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/webapi
    WEB_API_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-api" "service" "name") . }}:{{ tpl (index .Values "forms-flow-api" "service" "port") . }}
    {{- if .Values.mongodb.enabled }} 
    NODE_CONFIG: '{"mongo":"mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}"}'
    MONGODB_URI:  {{ ternary (tpl "mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }}
    {{- else }}
    MONGODB_URI:  {{ ternary (tpl "mongodb+srv://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }} 
    NODE_CONFIG: '{"mongo":"mongodb+srv://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}/{{ .Values.mongodb.auth.databases | first }}"}'
    {{- end }}
    FORMSFLOW_WEB_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}
    FORMSFLOW_WEB_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-web" "service" "name") . }}:{{ tpl (index .Values "forms-flow-web" "service" "port") . }}
    FORMSFLOW_ADMIN_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/admin/api/v1
    FORMSFLOW_ADMIN_BASE: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/admin/api
    FORMSFLOW_ADMIN_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-admin" "service" "name") . }}:{{ tpl (index .Values "forms-flow-admin" "service" "port") . }}/api/v1
    FORMSFLOW_ADMIN_BASE_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-admin" "service" "name") . }}:{{ tpl (index .Values "forms-flow-admin" "service" "port") . }}/api
    MODEL_ID: "Seethal/sentiment_analysis_generic_dataset"
    INSIGHT_API_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/redash
    INSIGHT_API_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-analytics" "service" "name") . }}:{{ tpl (index .Values "forms-flow-analytics" "service" "port") . }}
    KEYCLOAK_ENABLE_CLIENT_AUTH: "{{ index .Values "forms-flow-idm" "keycloak" "EnableKeycloakClientAuth" }}"
    MULTI_TENANCY_ENABLED: "{{ index .Values "forms-flow-web" "EnableMultitenant" }}"
    DATA_ANALYSIS_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/analysis
    DATA_ANALYSIS_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-data-analysis" "service" "name") . }}:{{ tpl (index .Values "forms-flow-data-analysis" "service" "port") . }}
    NODE_ENV: "production"
    CUSTOM_SUBMISSION_URL: "{{ .Values.custom_submission_url }}"
    CUSTOM_SUBMISSION_ENABLED: "{{ .Values.custom_submission_enabled }}"
    FORMSFLOW_DOC_API_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/docapi
    FORMSFLOW_DOC_API_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-documents-api" "service" "name") . }}:{{ tpl (index .Values "forms-flow-documents-api" "service" "port") . }}
    DRAFT_ENABLED: "{{ .Values.draft_enabled }}"
    DRAFT_POLLING_RATE: "15000"
    EXPORT_PDF_ENABLED: "{{ .Values.export_pdf_enabled }}"
    REDIS_HOST: "{{ .Values.redis_host }}"
    REDIS_PORT: "{{ .Values.redis_port }}"
    REDIS_ENABLED: "{{ .Values.EnableRedis }}"
    CHROME_DRIVER_PATH: "/usr/local/bin/chromedriver"
    ENABLE_CHATBOT: "{{ .Values.EnableChatBot }}"
    CHATBOT_URL: https://{{ tpl (index .Values "forms-flow-web" "ingress" "hostname") . }}/analysis/conversations
    CHATBOT_SERVICE_URL: http://{{ tpl (index .Values "forms-flow-data-analysis" "service" "name") . }}:{{ tpl (index .Values "forms-flow-data-analysis" "service" "port") . }}/conversations
    ENABLE_LOW_CODE_DESIGNER: "false"
    ELASTIC_SERVER: "{{ .Values.elastic_server }}"
    REDIS_URL: "{{ .Values.redis_url }}"
    IPAAS_EMBED_BASE_URL: "{{ .Values.ipaas.embed_base_url }}"
    IPAAS_API_BASE_URL: "{{ .Values.ipaas.api_base_url }}"
    CONFIGURE_LOGS: "{{ .Values.configure_logs }}"
    KEYCLOAK_URL_HTTP_RELATIVE_PATH: {{ index .Values "forms-flow-idm" "context-path" }}
    GUNICORN_WORKERS: "{{ .Values.gunicorn_workers }}"
    GUNICORN_THREADS: "{{ .Values.gunicorn_threads }}"
    GUNICORN_TIMEOUT: "{{ .Values.gunicorn_timeout }}"