---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  DATABASE_NAME: {{ ternary (tpl .Values.postgresql.auth.database .) "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  DATABASE_PORT: {{ ternary .Values.postgresql.primary.service.ports.postgresql "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  DATABASE_SERVICE_NAME: {{ ternary (tpl .Values.postgresql.fullnameoverride .) "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  BPM_API_URL: "https://formsflow-eks.aot-technologies.com/camunda"
  KEYCLOAK_JWT_OIDC_ALGORITHMS: "RS256"
  KEYCLOAK_JWT_OIDC_CACHING_ENABLED: "True"
  KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
  KEYCLOAK_JWT_OIDC_CONFIG: https://formsflow-eks.aot-technologies.com/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/.well-known/openid-configuration
  KEYCLOAK_JWT_OIDC_ISSUER: https://formsflow-eks.aot-technologies.com/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}
  KEYCLOAK_JWT_OIDC_JWKS_URI: https://formsflow-eks.aot-technologies.com/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/certs
  KEYCLOAK_TOKEN_URL: https://formsflow-eks.aot-technologies.com/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/token
  KEYCLOAK_URL: https://formsflow-eks.aot-technologies.com
  KEYCLOAK_URL_REALM: {{ index .Values "forms-flow-idm" "realm" }}
  FORMIO_URL: "https://formsflow-eks.aot-technologies.com/forms"
  FORMIO_DOMAIN: "https://formsflow-eks.aot-technologies.com/forms"
  WEB_API_URL: "https://formsflow-eks.aot-technologies.com/api"
  MONGODB_URI:  {{ ternary (tpl "mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }} 
  NODE_CONFIG:  {{ ternary (tpl "{\"mongo\":\"mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}\"}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }}
  FORMSFLOW_WEB_URL: "https://formsflow-eks.aot-technologies.com"
  FORMSFLOW_ADMIN_URL: "https://forms-flow-admin-{{.Release.Namespace}}.{{.Values.Domain}}/api/v1"
  FORMSFLOW_ADMIN_BASE: "https://forms-flow-admin-{{.Release.Namespace}}.{{.Values.Domain}}/api"
  MODEL_ID: "Seethal/sentiment_analysis_generic_dataset"
  INSIGHT_API_URL: "https://forms-flow-analytics-{{.Release.Namespace}}.{{.Values.Domain}}"
  KEYCLOAK_ENABLE_CLIENT_AUTH: "false"
  MULTI_TENANCY_ENABLED: "false"
  DATA_ANALYSIS_URL:  "https://forms-flow-data-analysis-{{.Release.Namespace}}.{{.Values.Domain}}"
  NODE_ENV: "production"
  CUSTOM_SUBMISSION_URL: ""
  CUSTOM_SUBMISSION_ENABLED: "false"
  FORMSFLOW_DOC_API_URL: "https://forms-flow-documents-api-{{.Release.Namespace}}.{{.Values.Domain}}"
  DRAFT_ENABLED: "false"
  DRAFT_POLLING_RATE: "15000"
  EXPORT_PDF_ENABLED: "false"
  REDIS_HOST: "{{.Values.redis_host}}"
  REDIS_PORT: "{{.Values.redis_port}}"
  REDIS_ENABLED: "false"


