---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  FORMIO_DEBUG: "formio:*"
  KEYCLOAK_JWT_OIDC_ALGORITHMS: "RS256"
  KEYCLOAK_JWT_OIDC_CACHING_ENABLED: "True"
  KEYCLOAK_JWT_OIDC_CONFIG: "https://$KEYCLOAK_URL/auth/realms/$KEYCLOAK_URL_REALM/.well-known/openid-configuration"
  KEYCLOAK_JWT_OIDC_ISSUER: "https://$KEYCLOAK_URL/auth/realms/$KEYCLOAK_URL_REALM"
  KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
  KEYCLOAK_JWT_OIDC_JWKS_URI: "https://$KEYCLOAK_URL/auth/realms/$KEYCLOAK_URL_REALM/protocol/openid-connect/certs"
  KEYCLOAK_TOKEN_URL: "https://$KEYCLOAK_URL/auth/realms/$KEYCLOAK_URL_REALM/protocol/openid-connect/token"
  KEYCLOAK_URL_REALM: "{{.Chart.Name}}"
  CAMUNDA_API_URI: "https://forms-flow-bpm-{{.Release.Namespace}}.{{.Values.Domain}}/camunda"
  KEYCLOAK_URL: "https://forms-flow-idm-{{.Release.Namespace}}.{{.Values.Domain}}"
  FORMIO_URL: "https://forms-flow-forms-{{.Release.Namespace}}.{{.Values.Domain}}"
  FORMSFLOW_API_URL: "https://forms-flow-webapi-{{.Release.Namespace}}.{{.Values.Domain}}"
