---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  DATABASE_NAME: {{ ternary (tpl .Values.postgresql.auth.database .) "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  DATABASE_PORT: {{ ternary .Values.postgresql.primary.service.ports.postgresql "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  DATABASE_SERVICE_NAME: {{ ternary (tpl .Values.postgresql.fullnameoverride .) "<DEFINE_ME>" .Values.postgresql.enabled | quote }}
  BPM_API_URL: "https://{{ .Values.Domain }}/camunda"
  KEYCLOAK_JWT_OIDC_ALGORITHMS: "RS256"
  KEYCLOAK_JWT_OIDC_CACHING_ENABLED: "True"
  KEYCLOAK_JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
  KEYCLOAK_JWT_OIDC_CONFIG: https://{{ .Values.Domain }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/.well-known/openid-configuration
  KEYCLOAK_JWT_OIDC_ISSUER: https://{{ .Values.Domain }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}
  KEYCLOAK_JWT_OIDC_JWKS_URI: https://{{ .Values.Domain }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/certs
  KEYCLOAK_TOKEN_URL: https://{{ .Values.Domain }}/auth/realms/{{ index .Values "forms-flow-idm" "realm" }}/protocol/openid-connect/token
  KEYCLOAK_URL: https://{{ .Values.Domain }}
  KEYCLOAK_URL_REALM: {{ index .Values "forms-flow-idm" "realm" }}
  FORMIO_URL: "https://{{ .Values.Domain }}/forms"
  FORMIO_DOMAIN: "https://{{ .Values.Domain }}/forms"
  WEB_API_URL: "https://{{ .Values.Domain }}"
  MONGODB_URI:  {{ ternary (tpl "mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }} 
  {{- if .Values.mongodb.enabled }} 
  NODE_CONFIG: '{"mongo":"mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}"}'
  {{- else }}
  NODE_CONFIG: "<DEFINE_ME>"
  {{- end }}
  FORMSFLOW_WEB_URL: "https://forms-flow-web-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  FORMSFLOW_ADMIN_URL: "https://forms-flow-admin-{{.Release.Namespace}}.{{tpl .Values.Domain .}}/api/v1"
  FORMSFLOW_ADMIN_BASE: "https://forms-flow-admin-{{.Release.Namespace}}.{{tpl .Values.Domain .}}/api"
  MODEL_ID: "Seethal/sentiment_analysis_generic_dataset"
  INSIGHT_API_URL: "{{ .Values.Analytics.Domain }}"
  KEYCLOAK_ENABLE_CLIENT_AUTH: "false"
  MULTI_TENANCY_ENABLED: "false"
  DATA_ANALYSIS_URL:  "https://forms-flow-data-analysis-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  NODE_ENV: "production"
  CUSTOM_SUBMISSION_URL: ""
  CUSTOM_SUBMISSION_ENABLED: "true"
  FORMSFLOW_DOC_API_URL: "https://{{ .Values.Domain }}/document"
  DRAFT_ENABLED: "{{.Values.draft_enabled}}"
  DRAFT_POLLING_RATE: "15000"
  EXPORT_PDF_ENABLED: "{{.Values.export_pdf_enabled}}"
  REDIS_HOST: "{{.Values.redis_host}}"
  REDIS_PORT: "{{.Values.redis_port}}"
  REDIS_ENABLED: "false"


