apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  KEYCLOAK_CLIENTID: "{{ .Values.bpm_keycloak_clientid }}"
  KEYCLOAK_CLIENTSECRET: "{{ .Values.bpm_keycloak_clientsecret }}"
  FORMIO_JWT_SECRET: "{{ .Release.Namespace }}-jwt-secret" 
  FORMIO_ROOT_EMAIL: "{{ .Values.formio_admin_email }}"
  FORMIO_ROOT_PASSWORD: "{{ .Values.formio_admin_password }}"
  WEB_CLIENTID: "{{ .Values.keycloak_web_clientid }}"
  WEBSOCKET_ENCRYPT_KEY: "{{ tpl .Values.websocket_encrypt_key .}}"
