apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
spec:
  replicas: {{ .Values.redisExporter.replica }}
  selector:
    matchLabels:
      app: redis-exporter
  serviceName: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.redisExporter.redis.image.registry }}/{{ .Values.redisExporter.redis.image.repository }}:{{ .Values.redisExporter.redis.image.tag }}"
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: client
          timeoutSeconds: 5
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "{{ .Values.redisExporter.resources.limits.cpu }}"
            memory: "{{ .Values.redisExporter.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.redisExporter.resources.requests.cpu }}"
            memory: "{{ .Values.redisExporter.resources.requests.memory }}"
        volumeMounts:
        - mountPath: /conf
          name: conf
          readOnly: true
        - mountPath: /data
          name: redis-data
          readOnly: false
      volumes:
      - configMap:
          defaultMode: 0555
          name: redis-exporter
        name: conf

  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.redisExporter.persistentVolumeClaim.size }}
      storageClassName: {{ .Values.redisExporter.persistentVolumeClaim.storageClass }}