apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.app_name }}
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.redis_exporter_name }}:{{ .Values.redis_exporter_tag }}"
        name: "{{ .Values.redis_exporter_name }}"
        ports:
        - containerPort: 9121
          name: exporter
      - command:
        - /conf/update-node.sh
        - redis-server
        - /conf/redis.conf
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.redis_image }}:{{ .Values.redis_tag }}"
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: client
          timeoutSeconds: 5
        name: redis
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1.5Gi
          requests:
            memory: 1.5Gi
        volumeMounts:
        - mountPath: /conf
          name: conf
          readOnly: true
        - mountPath: /data
          name: redis-data
          readOnly: false
      volumes:
      - configMap:
          defaultMode: 0555
          name: {{ .Chart.Name }}
        name: conf

  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage_size }}
      storageClassName: {{ .Values.storage_class }}
