---
keycloak:
  extraEnvVars: 
    - name: KEYCLOAK_ADMIN_USER
      value: admin
    - name: JAVA_OPTS
      value: >-
        -Dkeycloak.profile.feature.scripts=enabled
        -Dkeycloak.profile.feature.upload_scripts=enabled
        -Dkeycloak.migration.file=/realm/realm.json
        -Djava.net.preferIPv4Stack=true
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: "https://{{ tpl .Values.ingress.hostname . }}/auth"

  extraVolumes: 
    - name: "forms-flow-idm-realm-config"
      configMap:
        name: "forms-flow-idm"

  extraVolumeMounts: 
    - name: "forms-flow-idm-realm-config"
      mountPath: "/realm/"
      readOnly: true

  postgresql:
    auth:
      database: forms-flow-idm # Name for custom database to create
      postgresPassword: postgres # Password for the "postgres" admin user
      password: forms-flow-idm  # Password for the custom user to create
      userName: forms-flow-idm  # Name for a custom user to create
    image:
      registry: "docker.io"
      repository: "bitnami/postgresql" 
      tag: 14.2.0-debian-10-r57
    primary:
      containerSecurityContext:
        enabled: false
      persistence:
        mountPath: /var/lib/pgsql/data
        storageClass: nfs-client 
        size: 2Gi 
      podSecurityContext:
        enabled: false
      service:
        ports:
          postgresql: 5432  # PostgreSQL service port
      shmVolume:
        chmod:
          enabled: false
    volumePermissions:
      containerSecurityContext:
        runAsUser: "auto"

  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 1
      memory: 512Mi

  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false

  keycloakConfigCli:
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
  
  ingress:
    enabled: true
    extraTls:
      - {}
    hostname: "forms-flow-idm-formsflow-ai.apps.devops.aot-technologies.com"
    path: /auth
    pathType: Prefix
    servicePort: http
    tls: true
