---
apiVersion: v1
data:
  APP_SECURITY_ORIGIN: "*"
  CAMUNDA_ANALYTICS_DATABASE_SERVICE_NAME: "{{ .Values.camunda.analytics.database }}"
  CAMUNDA_APP_ROOT_LOG_FLAG: "{{ .Values.camunda.logLevel }}"
  CAMUNDA_AUTHORIZATION_FLAG: "{{ .Values.camunda.auth.enabled }}"
  CAMUNDA_AUTHORIZATION_REVOKE_CHECK_FLAG: "{{ .Values.camunda.auth.revokeCheck }}"
  CAMUNDA_DATABASE_NAME: "{{.Values.camunda.database.name}}"
  CAMUNDA_DATABASE_PORT: "{{.Values.camunda.database.port}}"
  CAMUNDA_FORMBUILDER_PIPELINE_USERNAME: "{{ .Values.camunda.formBuilder.username }}"
  CAMUNDA_HIKARI_CONN_TIMEOUT: "{{ .Values.camunda.hikari.timeout.connection }}"
  CAMUNDA_HIKARI_IDLE_TIMEOUT: "{{ .Values.camunda.hikari.timeout.idle }}"
  CAMUNDA_HIKARI_VALID_TIMEOUT: "{{ .Values.camunda.hikari.timeout.valid }}"
  CAMUNDA_HIKARI_MAX_POOLSIZE: "{{ .Values.camunda.hikari.poolsize.max }}"
  CAMUNDA_JDBC_DRIVER: "{{ .Values.camunda.jdbc.driver }}"
  CAMUNDA_JDBC_URL: "{{ tpl .Values.camunda.jdbc.url .}}"
  CAMUNDA_JDBC_USER: "{{ .Values.camunda.jdbc.username}}"
  WAIT_FOR: " {{ .Values.waitFor }}"  
  WEBSOCKET_MESSAGE_TYPE: "{{ .Values.camunda.websocket.messageType }}"
  WEBSOCKET_SECURITY_ORIGIN: {{ ternary  (.Values.camunda.websocket.securityOrigin | quote) (randAlphaNum 6 | quote) (kindIs "string" .Values.camunda.websocket.securityOrigin) }}
  BPM_BASE_URL: "https://{{tpl .Values.ingress.hostname .}}"
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
---
apiVersion: v1
data:
  mail-config.properties: |
    # send mails via SMTP
    mail.transport.protocol={{.Values.mail.protocol}}
    mail.smtp.auth={{.Values.mail.smtp.auth}}
    mail.smtp.host={{.Values.mail.smtp.server}}
    mail.smtp.port={{.Values.mail.smtp.port}}
    mail.smtp.ssl.enable={{.Values.mail.smtp.ssl.enable}}
    mail.smtp.socketFactory.port={{.Values.mail.smtp.socketFactory.port}}
    mail.smtp.socketFactory.class={{.Values.mail.smtp.socketFactory.class}}
    # poll mails via IMAPS
    #mail.store.protocol={{.Values.mail.store.protocol}}
    # mail.imaps.host={{.Values.mail.imaps.host}}
    mail.imaps.port={{.Values.mail.imaps.port}} 
    mail.imaps.timeout={{.Values.mail.imaps.timeout}}
    # additional config
    #mail.poll.folder={{.Values.mail.folder}}
    mail.sender={{.Values.mail.from}}
    mail.sender.alias={{.Values.mail.alias}}
    mail.attachment.download={{.Values.mail.attachment.download}}
    mail.attachment.path={{.Values.mail.attachment.path}}
    # credentials
    mail.user={{.Values.mail.user}}
    mail.password={{.Values.mail.password}}

kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}-mail-config
  name: {{ .Chart.Name }}-mail-config
---
{{- if .Values.elastic_search.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-fb-config
data:
  "filebeat.yml": |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /logs/*
    output.elasticsearch:
      hosts: "${ELASTIC_SERVER}"
      index: "forms-flow-bpm-%{+yyyy.MM.dd}"
    setup.template.name: "forms-flow-bpm"
    setup.template.pattern: "forms-flow-bpm-*"
    setup.template.overwrite: true
    setup.template.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
    setup.ilm.enabled: false 
{{- end }}   