apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations: null
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: "{{ .Chart.Name }}"
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - "{{ .Chart.Name }}"
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: APP_SECURITY_ORIGIN
          value: '*'
        - name: CAMUNDA_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: "{{ .Values.camunda_db_resource_name }}"
        - name: CAMUNDA_DATABASE_SERVICE_NAME
          value: "{{ .Values.camunda_db_resource_name }}"
        - name: CAMUNDA_JDBC_DRIVER
          value: "{{ .Values.postgre_db_driver }}"
        - name: CAMUNDA_JDBC_URL
          value: "jdbc:postgresql://${CAMUNDA_DATABASE_SERVICE_NAME}:{{ .Values.database_port }}/${CAMUNDA_DATABASE_NAME}"
        - name: WAIT_FOR
          value: "${CAMUNDA_DATABASE_SERVICE_NAME}:{{ .Values.database_port }}"
        - name: CAMUNDA_JDBC_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: "{{ .Values.camunda_db_resource_name }}"
        - name: CAMUNDA_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: "{{ .Values.camunda_db_resource_name }}"
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: KEYCLOAK_URL_REALM
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_URL_REALM
              name: "{{ .Values.formsflow_config_name }}"
        - name: KEYCLOAK_CLIENTID
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_ID
              name: "{{ .Values.formsflow_secret }}"
        - name: KEYCLOAK_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              key: BPM_CLIENT_SECRET
              name: "{{ .Values.formsflow_secret }}"
        - name: MAIL_CONFIG
          value: /app/mail-config.properties
        - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
          value: "{{ .Values.camunda_formbuilder_pipeline_username }}"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
          value: "{{ .Values.camunda_formbuilder_pipeline_password }}"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
          valueFrom:
            configMapKeyRef:
              key: CAMUNDA_API_URI
              name: "{{ .Values.formsflow_config_name }}"
        - name: CAMUNDA_HIKARI_CONN_TIMEOUT
          value: "{{ .Values.camunda_hikari_connection_timeout }}"
        - name: CAMUNDA_HIKARI_IDLE_TIMEOUT
          value: "{{ .Values.camunda_hik_idle_timeout }}"
        - name: CAMUNDA_HIKARI_MAX_POOLSIZE
          value: "{{ .Values.camunda_hikari_maximum_poolsize }}"
        - name: CAMUNDA_HIKARI_VALID_TIMEOUT
          value: "{{ .Values.hikari_valid_timeout }}"
        - name: CAMUNDA_ANALYTICS_DATABASE_SERVICE_NAME
          value: "{{ .Values.analytics_db_resource_name }}"
        - name: CAMUNDA_ANALYTICS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: CAMUNDA_BPM_HISTORY_LEVEL
          value: none
        - name: CAMUNDA_AUTHORIZATION_FLAG
          value: "true"
        - name: CAMUNDA_AUTHORIZATION_REVOKE_CHECK_FLAG
          value: auto
        - name: CAMUNDA_APP_ROOT_LOG_FLAG
          value: "{{ .Values.camunda_app_root_log_flag }}"
        - name: FORMSFLOW_API_URL
          valueFrom:
            configMapKeyRef:
              key: WEB_API_BASE_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: FORMIO_URL
          valueFrom:
            configMapKeyRef:
              key: FORMIO_URL
              name: "{{ .Values.formsflow_config_name }}"
        - name: FORMIO_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_EMAIL
              name: "{{ .Values.formsflow_secret }}"
        - name: FORMIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: FORMIO_ROOT_PASSWORD
              name: "{{ .Values.formsflow_secret }}"
        - name: WEBSOCKET_ENCRYPT_KEY
          valueFrom:
            secretKeyRef:
              key: WEBSOCKET_ENCRYPT_KEY
              name: "{{ .Values.formsflow_secret }}"
        - name: WEBSOCKET_MESSAGE_TYPE
          value: "{{ .Values.websocket_message_type }}"
        - name: WEBSOCKET_SECURITY_ORIGIN
          value: "{{ .Values.websocket_security_origin }}"
        image: "{{ tpl .Values.image_url . }}:{{ .Values.image_tag }}"
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /camunda/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        name: "{{ .Chart.Name }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /camunda/actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "{{ .Values.cpu_limit }}"
            memory: "{{ .Values.memory_limit }}"
          requests:
            cpu: "{{ .Values.cpu_request }}"
            memory: "{{ .Values.memory_request }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/mail-config.properties
          name: "{{ .Chart.Name }}-mail-config"
          subPath: mail-config.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mail-config.properties
            path: mail-config.properties
          name: "{{ .Chart.Name }}"
        name: "{{ .Chart.Name }}-mail-config"
