---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD: "{{ .Values.camunda.formBuilder.password }}"

