---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.redis_image }}
spec:
  tags:
  - from:
      kind: DockerImage
      name: "image-registry.openshift-image-registry.svc:5000/openshift/{{ .Values.redis_image }}:{{ .Values.redis_tag }}"
    name: "{{ .Values.redis_tag }}"
    referencePolicy:
      type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .Values.redis_exporter_name }}"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "registry.hub.docker.com/{{ .Values.redis_exporter_image }}:{{ .Values.redis_exporter_tag }}"
    name: "{{ .Values.redis_exporter_tag }}"
    referencePolicy:
      type: Local
