name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      region:
        required: true
jobs:
  jobName:
    name: Update deploy
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}  # Change this to your desired region
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Update Kube config
        run: aws eks update-kubeconfig --region ca-central-1 --name forms-flow-eks-staging
      - name: Deploy to eks
        run: |
          kubectl -n qa rollout restart deployment/forms-flow-web
