{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-idm
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  HUBSPOT_BASE_URL: "{{ .Values.HubspotBaseUrl }}"
  HUBSPOT_ACCESS_TOKEN: "{{ .Values.HubspotAccessToken }}"
  HUBSPOT_PIPELINE_ID: "{{ .Values.HubspotPipelineId }}"
  HUBSPOT_DEAL_STAGE_ID: "{{ .Values.HubspotBaseDealStageId }}"
  HUBSPOT_OWNER_ID: "{{ .Values.HubspotOwnerId }}"
  HUBSPOT_DEAL_SOURCE: "{{ .Values.HubspotDealSource }}"
{{- end }}